### ISSUE TITLE
Will this work with the 10.5 inch Pervasive Displays display?

### ISSUE THREAD

**Issue by setpixel** [andrei7c4/weatherdisplay#1]
Hi! Really great project.

I was wondering if you know if the functions on the 7.5 inch would also work with the 10.5 inch eink display?

Obviously the resolution is different, so I wouldn't assume it would magically work as a drop in replacement. 

Just curious if you looked into that.

**Comment by andrei7c4** [comment]
Hi,
The problem with 10" display is that it has much higher resolution
(1024x1280) compared to 7" display (480x800). ESP8266 does not have enough
RAM for the frame buffer that size. Actually, even for 7" display the
buffer is only half of the display's height. This is possible because user
interface can be easily divided into two parts - top and bottom, so only
one half need to be buffered at a time. So unless you find a way how to
naturally divide user interface into four parts, it may not be possible to
use 10" display. Otherwise, the 10" display seems to have similar SPI
interface as the 7" display, so no significant code modifications are
needed.

Andrei
