### ISSUE TITLE
Forcast Daily

### ISSUE THREAD

**Issue by joklcr** [andrei7c4/weatherdisplay#2]
Hi, i have flashed esp8266 and Epaper Display display does not work.
there is an issue:
( Serial monitor)
------------------------------------
onTcpDataReceived 510
parseHttpReply 510
HTTP/1.1 401 Unauthorized
Server: openresty
Content-Type: application/json; charset=utf-8
Content-Length: 107
Connection: keep-alive
X-Cache-Key: /data/2.5/forecast/daily?APPID=(myAPI Codexxxxxxx)&cnt=3&id=2939778&lang=en&mode=json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST

{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

parse forecastDaily failed  <------
--------------------------------------

In Openweathermap free account ist not include   "16 days/daily forecast API"       
Startup Account 40 USD / month ????

**Comment by andrei7c4** [comment]
Hi,
Thanks for informing me. It seems that OpenWeatherMap has recently changed their pricing and the daily API (forecast16) is indeed not free anymore. However, it is still free for old accounts, like mine. That's why I have not noticed the issue myself. Other projects are facing the same issue: https://github.com/MichMich/MagicMirror/issues/1017

I will reimplement the code to use forecast5 API which is still free.

Andrei

**Comment by andrei7c4** [comment]
I have now removed the use of forecast16 API so only the free APIs (current weather and 5 days/3 hour forecast) are used. Daily forecast is formed locally from hourly data. There were no need to change the GUI.
