### ISSUE TITLE
German language

### ISSUE THREAD

**Issue by samyness** [andrei7c4/weatherdisplay#8]
Hey,
is it possible to add ä, ö, ü and ß to arial56? -> For example German weather discription in Chart 2 "Mäßiger Regen“ is displayed as "Miger Regen". 
The problem is that the according chars are not defined in arial56.c, right? 

So, how is the .fnt file with the png converted to the .c file?

Thank you in advance!
Samuel

**Comment by andrei7c4** [comment]
Font .c files are generated with a tool that I have not publish yet. I need to clean-up the code first.

But the problem is not only the font. You also need to parse unicode from the reply. I have implemented unicode support in my Spotify project, but for this project, I think it would be an overkill (and might not fit in memory). It might be possible to implement some kind of "light unicode" support which would be able to parse Latin-1 Supplement page only, but I cannot promise anything.
